### ISSUE TITLE
Clean up repo

### ISSUE THREAD

**Issue by Marcus-Friis** [group-o-minitwit-2024/MiniTwit#38]
Remove files such as [schema.sql](https://github.com/group-o-minitwit-2024/MiniTwit/blob/471b7a7201db88d438a8f447cec7e53965f3179b/schema.sql) and [utils/dbUtils.js](https://github.com/group-o-minitwit-2024/MiniTwit/blob/main/utils/dbUtils.js). 

Addtionally, it would be nice a directory cleanup, such that it is easier to navigate.

**Comment by JoakimAustvold** [comment]
consider removing vagrant file?

**Comment by JoakimAustvold** [comment]
minitwit test
schema.sql
vagrant
log that hasnt been used in a long time

distinction of service
create a folder for api application,  shared dependencies

**Comment by JoakimAustvold** [comment]
second iteration with dev stuff
